# Generated by Django 3.1.5 on 2021-02-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
