# Generated by Django 3.1.5 on 2021-02-13 11:27

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField(unique=True)),
                ('address', models.TextField(null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=100, null=True, validators=[django.core.validators.EmailValidator('Invalid Email Adderss')])),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('u', 'Undesclosed')], max_length=1, null=True)),
                ('slug', models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
            ],
        ),
    ]
