# Generated by Django 3.1.5 on 2021-02-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_playground', '0002_auto_20210213_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
    ]
